### ISSUE TITLE
TracingView: Picking/Transforming not as desired

### ISSUE THREAD

**Issue by draaw** [SiLeBAT/BfROpenLab#376]
- Picking is possible only by pressing a key
- Transforming in explosion view results in moved stations - away from the frame

**Comment by ruegenbfr** [comment]
The transforming issue was transferred to a new ticket (#388).

**Comment by ruegenbfr** [comment]
Picking a single item works without pressing a key (like in the old days). Picking multiple items works only with pressing the shift key, because the shift key tells the system that the user does not want to transform the graph but to change add a selection. This behaviour is consistent with the web app.
